Change the script for reactivation proxy clients to use the salt-bundle
uyuni-project/contrib pull request #19
Opened 2023-10-17 09:36 UTC by avshiliaev

2023-10-17 11:41 UTC, aaannz commented
I wonder if this script is still needed. When it was written, reactivation was only way to update proxy path. But in current 4.3 and uyuni, proxy path is by regular minion start handler.

2023-10-19 09:59 UTC, admd commented
@aaannz we still have this original problem of minions being disappeared. Reboot of minions is not helping. User have to onboard those minions again apparently.

2023-10-20 14:28 UTC, avshiliaev commented
@aaannz thanks for your feedback. Would please take another look at the changes?

2023-10-20 14:36 UTC, aaannz requested changes
You are still missing correct salt minion service restart.

Currently it's calling `suma_salt.cmd(c, "cmd.run_bg", ["sleep 2;service salt-minion restart"])`. That is fine for salt-minion, but not venv-salt-minion.

So on top of differentiating config files, you also need to have different service names.

2023-10-20 14:37 UTC, aaannz commented on uyuni-tools/reactivate_proxy_clients.py
> +            else "/etc/salt/minion.d/susemanager.conf"
Here you need expanded if so you can set both client configpath and also client service name (`salt-minion` vs. `venv-salt-minion`)

2023-10-20 16:46 UTC, aaannz approved these changes
LGTM. Thanks!

2023-10-26 14:14 UTC, merged